### ISSUE TITLE
[docs] Reorganize them to make more sense

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#162]
```
Overview
QuickStart
Server
    Overview
    Configuration
    ...
Actions
    Overview
    check kubernetes
    check service
    ....
Configuration
    Overview
    credentials
    checks
    ...
Clients
    Overview
    CLI
    Slack
```

@thuey Thoughts?

**Comment by thuey** [comment]
I like it, with possibly one exception. Do you think it's better to have the configuration live alongside the action or is it more important that all of the configuration documentation is in one place? I'm torn.

**Comment by thuey** [comment]
Also, I think we will quickly need to nest the actions together, such as /check/kubernetes, /check/service

**Comment by jonnymbgood** [comment]
We have config that isn't 1-to-1 with actions (pleaseops, credentials). I propose we try it separate for now and see how it works out. Merging them back together shouldn't be difficult.

Also, I agree about the nesting. Let's re-evaluate that once we are closer to going live or we get a lot more actions/targets.
