### ISSUE TITLE
[meta] finalize create/grant/revoke/delete syntax

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#175]
add vs put/set
remove vs delete

**Comment by jonnymbgood** [comment]
* `please create role admin`
* `please grant role admin permission "a b c"`
* `please create user jdoe`
* `please grant user jdoe role admin`
* `please revoke user jdoe role admin`
* `please revoke role admin permission "a b c"`
* `please delete user jdoe`
* `please delete role admin`

@thuey Thoughts?

**Comment by thuey** [comment]
Looks good!

**Comment by jonnymbgood** [comment]
👍
