### ISSUE TITLE
[meta] changelog

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#177]
@thuey What should we do about generating/keeping a changelog? Generate off of commit messages using a tool? What tool? Thoughts?

**Comment by thuey** [comment]
It seems like commit messages would be too granular, unless we just based it on the squash commit to master by filtering out the list of commit messages within the squash. How about we just base it on PR messages?

I've used this before, but it's based on Ruby: https://github.com/github-changelog-generator/github-changelog-generator :/ It does have a docker image you could run, though.

**Comment by jonnymbgood** [comment]
What do you think about hand crafting the commit log? We have to update the roadmap and features list by hand anyway. Or should we just plan on doing it by hand until it becomes a big enough pain that we automate it?

As an aside, it is kind of nice to do a retrospective when going through the commits and generating the Changelog. Thoughts?

**Comment by thuey** [comment]
That's valid. I'm fine handcrafting for now.

**Comment by jonnymbgood** [comment]
Ok. I've been reading about [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) https://www.conventionalcommits.org/en/v1.0.0-beta.4/ 

We may want to use something like this in the future.
