### ISSUE TITLE
[server] warn when granting or revoking overlapping permissions

### ISSUE THREAD

**Issue by thuey** [pleaseops/pleaseops#204]
When a user is granting or revoking a permission that overlaps with another permission, they might be confused later on when a user has access to something that they should not.

1. When granting an overlapping permission to a user or role, show a warning that includes the overlapping permissions. For example:
```
/please grant role dev permission "check k8s *"
```
```
/please grant user role dev
```
```
/please grant user jsmith permission "check k8s *"
```
```
/please grant user jsmith permission "check k8s prod"
```
> Warning: User jsmith already has permission to "check k8s prod" through the following permission grants:
> - "check k8s *"
> - "check k8s *" through role dev

When revoking a permission where a user or role will still have access through another permission grant, show a warning. For example:
1. When granting an overlapping permission to a user or role, show a warning that includes the overlapping permissions. For example:
```
/please grant user jsmith permission "check k8s prod"
```
```
/please grant user jsmith permission "check k8s *"
```
```
/please revoke user jsmith permission "check k8s prod"
```
> Warning: User jsmith will still have permission to "check k8s prod" through the following permission grants:
> - "check k8s *"

**Comment by thuey** [comment]
@jonnymbgood Thoughts?

**Comment by jonnymbgood** [comment]
Looks good. We can implement the first warning when we implement assigning user permissions directly. (right now you can only grant permissions to roles and grant roles to users).
