### ISSUE TITLE
[meta] use ssh keys to authenticate client

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#234]
* `please associate pleaseops user foo with publicKey ...`
* server accepts public key
* client uses privateKey to sign JWT (verified server-side)

**Comment by jonnymbgood** [comment]
@thuey Thoughts?

**Comment by thuey** [comment]
Sounds good. I'm assuming the JWT generating would be transparent to the user?

Some alternative syntaxes to try to make the command shorter:
- `please set pleaseops user foo publicKey ...`
- `please add pleaseops user foo publicKey ...`

**Comment by jonnymbgood** [comment]
Per our conversation, how about `please login pleaseops cli` from slack and `please login pleaseops --token=1234` from the cli?

**Comment by jonnymbgood** [comment]
I like `please set pleaseops user foo publicKey 1234...`. Thoughts?

@thuey

**Comment by thuey** [comment]
What would login from the cli do? Is this for opening the web UI? If not, then are you thinking it would write the token to a temp file or env variable? Otherwise, wouldn't you have to include --token on every request still?

**Comment by thuey** [comment]
I like `please set`

**Comment by jonnymbgood** [comment]
The login call from the cli uses the temporary token (issued through slack to identify the user and only usable once) to authenticate the call to set the user's public key. Every subsequent call would use the normal jwt process where we sign the jwt with the user's private key and verify it using the public key.

Essentially we give the user a temporary key in slack that they use in the cli to upload their public key. After that they are using the regular public/private key signing for each request.

**Comment by thuey** [comment]
I guess I'm just thrown off by the `please login pleaseops
--token=1234 `. Wouldn't
it just be `please set pleaseops user foo publicKey ... --token=123` or
something like that?

**Comment by jonnymbgood** [comment]
So we have a choice. We could do `please set pleaseops user foo publicKey <base64encodedpublickey> --token=123` where they need to get their public key, base64 encode it, and piece together the command themselves. Or we could do it for them via a cli only command (like `please login pleaseops --token=123`)

I'm leaning toward the latter because we can give them the command to run as the output of the slack command.
```text
# in slack
/please login pleaseops cli
    To login to pleaseops from the cli, please run the following command from your terminal:
    please login pleaseops --token=1234
    Note that this token is good for a single use in the next 5 minutes.
    < link to releases page to download cli >
# in cli
$> please login pleaseops --token=1234
   Public key (~/.ssh/id_rsa.pub):
   PleaseOps Server (https://pleaseops.mycompany.com):
   Public key set. You are now logged in.
```

vs.

```text
# in slack
/please login pleaseops cli
    The following token is good for a single use in the next 5 minutes.
    Please base64 encode your ssh public key and call the following command with your token:
    please set pleaseops user foo publicKey <yourbase64encodedpublickey> --token=123
    On mac or linux you can get your key and base64 encode by ...
    On windows you can get your key and base64 encode by ...
    < link to releases page to download cli >
# in cli
$> cat ~/.ssh/id_rsa.pub | base64
  32b49e4f...
$> please set pleaseops user foo publicKey 32b49e4f... --token=123
$> PleaseOps Server (https://pleaseops.mycompany.com):
$> Public key set.
```

**Comment by jonnymbgood** [comment]
We could also support `please login pleaseops cli` from slack where you pass your publickey in.
```text
# in slack
/please login pleaseops cli 32b49e4f...
```
This is the command that the cli only command can proxy under the covers.

**Comment by jonnymbgood** [comment]
Another reason we may want to use `login pleaseops` over `set pleaseops user` is permissions. We can set the permissions for `login pleaseops` to not require any specific permissions other than the user exist in pleaseops. `set pleaseops user` overlaps with commands that may need to be permissioned, but we _could_ do a bypass on certain set commands that reference the calling user (we wouldn't want users setting the private keys of other users unless specifically granted permissions).

**Comment by jonnymbgood** [comment]
@thuey Thoughts?

**Comment by thuey** [comment]
I don't feel super strong on this, so if you do, go with what you think is best. However, here are my thoughts...

I think `login` would be a bit of a misnomer with what's actually happening.

For permissioning, I think there will be other things we will need to whitelist if a user is performing an action on themselves. Although, I will admit that none come to mind immediately.

**Comment by jonnymbgood** [comment]
I think we can close this for now since the cli is dying.
