### ISSUE TITLE
[config] separate config by types (actions/users/roles/etc...)

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#240]
Proposal:
```text
actions/
roles/
users/
```

**Comment by jonnymbgood** [comment]
@thuey Thoughts?

**Comment by thuey** [comment]
What do you think of `commands` instead of `actions`? That way, a `command` is the join between an `action` and a `resource`?

**Comment by jonnymbgood** [comment]
I'd be ok with that. Should I roll that into this change?

**Comment by thuey** [comment]
I think that would be great, unless that's too big of a change
