### ISSUE TITLE
[meta] decide on update syntax

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#75]
We have several things we can update in the config

* credentials (i.e.`credentials.aws.primary` ->`obj`)
* login (i.e.`login.aws.admin` ->`obj`)
* check (i.e.`check.k8s.cluster` ->`obj`)
* users (i.e.`users.jclark` ->`obj`)
* roles (i.e.`roles.admin` ->`obj`)
* ...

They all follow the format of `thing, type, id, and properties` or `thing, id, properties`. It would be nice if we could set everything using the same please syntax.

Some options:
* `please set user jclark`
* `please update role admin`
* `please put credentials aws primary`

We could also flatten the credentials and action blocks to loginAws, credentialsAws, checkK8s, etc...

@thuey Thoughts?

**Comment by jonnymbgood** [comment]
Maybe we can use 2 commands, one for adding and one for removing, that work in all cases. The difficulty I have been struggling with is how to handle arrays. But we do know that we won't have dupes in our arrays, so maybe an idempotent add and delete will work.

* `please add user jclark roles admin`
* `please remove role developer permissions login:*:*`

**Comment by jonnymbgood** [comment]
Maybe `get`, `set`, and `delete` would work, but then we could't use get for other things other than config getting...

**Comment by jonnymbgood** [comment]
If we use `please show` for getting external things, I think we can use `get`, `set`, and `delete` for modifying the config. I think we can go ahead and move in this direction.

**Comment by thuey** [comment]
I like `get`, `set`, and `delete`. Couldn't we still use `get` for other things if we include `config` as the target? For example:

- `please set config credential aws primary encryptedSecretKey skljfglkajdshflkjhadfs`
- `please get config credential aws primary`
- `please get delete config credential aws primary`

I realize that this makes the command a little more verbose. However, isn't that more consistent with how other commands will be?

**Comment by jonnymbgood** [comment]
I'm a little uncomfortable with using get for config values and other things. The type goes from being something like `credentials` or `users` to `config`, and the target id can't be the id of the thing anymore. And it just feels weird. I'll think on this a little more and hopefully give you a better reason against, but if possible I would prefer reserving get/set/delete for config management only, and some other descriptor for getting information from external tools. Or using another trio of actions for config and reserving get for other systems. Either or.

**Comment by jonnymbgood** [comment]
What if we used `please get pleaseops config`? we could add some options to get specific parts of the config, and then it matches `please get k8s app` or `please get rds backup`.

**Comment by jonnymbgood** [comment]
Or we could have multiple ids, one per block (`please get pleaseops users`, `please get pleaseops roles`, `please get pleaseops credentials`, etc...). This would probably mean re-pluralizing things :)

**Comment by jonnymbgood** [comment]
Based on our discussion yesterday we are going with `please get pleaseops config`, `please set pleaseops users`, and `please delete pleaseops credentials`
