### ISSUE TITLE
login vs log in vs sign in vs signin

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/pleaseops#9]
Since our commands will/should mostly be in the format of `please [action] [thing]` it would be nice if the action was a single word for cli integration. As such, my preference would be for `signin` or `login` over `sign in` or `log in`. We could make either work, but I think a single word would be preferential.

@thuey Thoughts?

**Comment by thuey** [comment]
My preference is for it to be a single word. Although, I'm conflicted over
being grammatically correct.

**Comment by jonnymbgood** [comment]
it looks like expediency wins out on this one, especially since `please log` may be a thing. `please login` it is. 

Closing...
